from google import genai
from dotenv import load_dotenv

import os
import pyttsx3
import sys
import pyaudiowpatch as pyaudio
import json

from api_tools import TOOLS


sys.modules["pyaudio"] = pyaudio

import speech_recognition as sr


# =========================
# ENVIRONMENT SETUP
# =========================

load_dotenv()


GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")


if not GEMINI_API_KEY:
    raise ValueError(
        "GEMINI_API_KEY is missing from .env"
    )


client = genai.Client(
    api_key=GEMINI_API_KEY
)


# =========================
# FRIDAY PERSONALITY
# =========================

SYSTEM_INSTRUCTION = """
You are Friday, a personal AI assistant.

Your personality is intelligent, calm, professional,
helpful and slightly witty.

You should:

- Give direct and useful answers.
- Avoid unnecessary explanations unless requested.
- Speak naturally because your responses are converted to speech.
- Never mention that you are following a system instruction.
- Never pretend to have performed an action that you did not perform.
- When the user asks for instructions, give clear step-by-step instructions.
"""


# =========================
# GEMINI
# =========================

def ask_gemini(prompt):

    response = client.models.generate_content(

        model="gemini-3.6-flash",

        contents=prompt,

        config={
            "system_instruction": SYSTEM_INSTRUCTION
        }
    )

    return response.text


# =========================
# INTENT DETECTION
# =========================

def detect_intent(prompt):

    tool_instruction = """
You are FRIDAY's action planner.

Your job is to understand what the user wants and decide
whether FRIDAY should perform an action using one or more
available tools.

Available tools:

1. open_application

Arguments:
- app_name

Purpose:
Opens an application using Windows search.

2. search_browser

Arguments:
- query

Purpose:
Searches Google using the user's default browser.

3. type_text

Arguments:
- text

Purpose:
Types text using the keyboard into the currently focused
application.

IMPORTANT:
The text can be generated by you.

For example, if the user says:

"Write a random to-do list."

You should generate the to-do list yourself and put the
complete generated list inside the "text" argument.

Do NOT tell the user to manually type it.

4. send_email

Arguments:
- recipient
- subject
- body
- attachments
- cc
- bcc

Purpose:
Sends an email.

You may use multiple tools when the user requests multiple
actions.

For example:

"Open Notepad and write a random to-do list."

should result in two tool calls:

1. open_application
2. type_text

The second tool call should contain the actual to-do list
generated by you.

Another example:

"Open Word and write a short project introduction."

should result in:

1. open_application
2. type_text

The type_text content should be generated by you.

Return ONLY valid JSON.

Do not use Markdown.

Do not add explanations.

If no tool is required, return:

{
    "tool_calls": []
}

If tools are required, return:

{
    "tool_calls": [
        {
            "tool": "tool_name",
            "arguments": {}
        }
    ]
}

Execute tool calls in the correct order.

Never invent a tool.

For email:
- Create a suitable subject if the user does not provide one.
- Use null for attachments if none are mentioned.
- Use null for cc if none are mentioned.
- Use null for bcc if none are mentioned.
"""


    response = client.models.generate_content(

        model="gemini-3.6-flash",

        contents=prompt,

        config={
            "system_instruction": tool_instruction
        }
    )

    return response.text


# =========================
# TOOL EXECUTION
# =========================

def execute_tool(prompt):

    result = detect_intent(prompt)

    try:

        cleaned = result.strip()

        if cleaned.startswith("```json"):
            cleaned = cleaned[7:]

        elif cleaned.startswith("```"):
            cleaned = cleaned[3:]

        if cleaned.endswith("```"):
            cleaned = cleaned[:-3]

        tool_request = json.loads(
            cleaned.strip()
        )

    except (
        json.JSONDecodeError,
        AttributeError
    ):

        return None


    tool_calls = tool_request.get(
        "tool_calls",
        []
    )


    if not isinstance(tool_calls, list):
        return None


    if not tool_calls:
        return None


    results = []


    for call in tool_calls:

        if not isinstance(call, dict):
            continue


        tool_name = call.get("tool")

        arguments = call.get(
            "arguments",
            {}
        )


        if not isinstance(arguments, dict):

            return (
                "I couldn't understand "
                "the tool arguments."
            )


        tool = TOOLS.get(tool_name)


        if tool is None:

            return (
                f"I don't have permission "
                f"to use {tool_name}."
            )


        try:

            result = tool(
                **arguments
            )

            results.append(
                str(result)
            )

        except Exception as error:

            return (
                f"I couldn't complete "
                f"that action: {error}"
            )


    if not results:
        return None


    return " ".join(results)


# =========================
# TEXT TO SPEECH
# =========================

def speak(text):

    engine = pyttsx3.init()

    voices = engine.getProperty(
        "voices"
    )


    if len(voices) > 1:

        engine.setProperty(
            "voice",
            voices[1].id
        )


    engine.say(text)

    engine.runAndWait()


# =========================
# SPEECH RECOGNITION
# =========================

def listen():

    recognizer = sr.Recognizer()


    with sr.Microphone(
        device_index=2
    ) as source:

        print("Listening...")


        recognizer.adjust_for_ambient_noise(
            source,
            duration=1
        )


        try:

            audio = recognizer.listen(
                source,
                timeout=None,
                phrase_time_limit=None
            )

        except sr.WaitTimeoutError:

            return None


    try:

        print("Recognizing...")


        prompt = recognizer.recognize_google(
            audio
        )


        print(
            f"You said: {prompt}"
        )


        return prompt


    except sr.UnknownValueError:

        print(
            "Sorry, I could not "
            "understand the audio."
        )

        return None


    except sr.RequestError as error:

        print(
            f"Could not request results; "
            f"{error}"
        )

        return None


# =========================
# CONVERSATION STORAGE
# =========================

CONVERSATION_FILE = os.path.join(

    os.path.dirname(
        os.path.abspath(__file__)
    ),

    "storage",

    "conversation.json"
)


def load_conversation():

    if not os.path.exists(
        CONVERSATION_FILE
    ):

        return []


    try:

        with open(
            CONVERSATION_FILE,
            "r",
            encoding="utf-8"
        ) as file:

            conversation = json.load(file)


            if isinstance(
                conversation,
                list
            ):

                return conversation


            return []


    except (
        json.JSONDecodeError,
        OSError
    ):

        return []


def save_conversation(
    conversation
):

    os.makedirs(
        os.path.dirname(
            CONVERSATION_FILE
        ),
        exist_ok=True
    )


    with open(
        CONVERSATION_FILE,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(

            conversation,

            file,

            indent=4,

            ensure_ascii=False
        )


def process_prompt(prompt):

    answer = ask_gemini(
        prompt
    )


    conversation = load_conversation()


    conversation.append({

        "user": prompt,

        "friday": answer
    })


    save_conversation(
        conversation
    )


    return answer


# =========================
# FRIDAY COMMAND HANDLER
# =========================

def handle_prompt(prompt):

    tool_result = execute_tool(
        prompt
    )


    if tool_result is not None:

        return tool_result


    return process_prompt(
        prompt
    )


# =========================
# MAIN PROGRAM
# =========================

def main():

    while True:

        prompt = listen()


        if prompt is None:
            continue


        command = prompt.lower().strip()


        if command in [
            "exit",
            "quit",
            "stop",
            "goodbye"
        ]:

            speak("Goodbye!")

            break


        answer = handle_prompt(
            prompt
        )


        print(
            f"Friday: {answer}"
        )


        speak(answer)


# =========================
# PROGRAM START
# =========================

if __name__ == "__main__":

    main()
